key = "dfdsfds" # the GaodeMap key
transit_data_path = "" # path to transit data, example："/Users/zeyuan.li/transit.csv"
driving_data_path = "" # path to driving data, example："/Users/zeyuan.li/driving.csv"