key = "9646e40dd9d578984c0aa3d7b972d29a" # the GaodeMap key

# path to driving data, example："/Users/zeyuan.li/driving.xlsx"
driving_data_path = "./bin/driving_template.xlsx"

# scheduled task expression; start only once："once"  Parser: https://en.wikipedia.org/wiki/Cron
driving_task = "once"
#driving_task = "*/1 * * * *"

transit_data_path = "" # path to transit data, example："/Users/zeyuan.li/transit.csv"
